### ISSUE TITLE
Should the SQLite.Native package work with a net461 console app using project.json?

### ISSUE THREAD

**Issue by ericsink** [natemcmaster/libsqlite3-package#9]
Apologies if this is not an appropriate place to post this, which is likely to be more of a question than a bug. 

I am trying to understand the issues of how to use the runtimes feature in a nuspec.  I got here from your blog entry on "The Runtime ID Graph".  My particular interest is in how things work for a nuget package that contains only native code, so this repo seems relevant.

Also, my focus here is on how the nuget v3 features work, not on how to make things work for nuget 2.  I see these nuget v3 features as an opportunity to eventually move away from .targets and .props files to deal with native libraries.  I do see that this nupkg contains those things, apparently for backwards compatibility.

So anyway:

First I create a console app project (Visual Studio 2015 Update 3, net461).  

Then I add a project.json file (by hand, using steps similar to the "project.json all the things" blog entry by @onovotny.

Then I add the SQLite.Native.3.12.2.nupkg.  This shows up nicely in project.json as I would expect.

Then I rebuild.

What I would expect here is that sqlite3.dll would get added to the build output directory, but that doesn't seem to happen.

The project.lock.json definitely contains new stuff that came from the addition of the package.

I get the same result whether I am building for AnyCPU or x64 (which, by the way, required me to add "win-x64" to the runtimes section of the project.json file).

I suspect I am doing something wrong due to a poor understanding on my part.  Can you offer any clues?

Thanks!

**Comment by natemcmaster** [comment]
All of the tech exists to make project.json + csproj work in the VS2015 release, but only the .NET Core SDK (.xproj + project.json) actually ties them all together in way the makes a usable experience. As [announced in May](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/), tooling updates will come soon to MSBuild to support scenarios such as this out-of-box.

Until those updates are available, you have two choices: 
1 - Use the project.json + xproj tooling to create a net461 console app.
2 - Use lower-level MSBuild components directly. NuGet 3 for MSBuild was designed for Universal Windows apps, but with a good understanding of [NuGet's MSBuild targets](https://github.com/NuGet/NuGet.BuildTasks/blob/visual-studio-2015-update-3/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.targets), you can make it do what you want. This is advanced stuff and VS doesn't surface UI for this kind of stuff.

**Comment by natemcmaster** [comment]
For option 2, see https://gist.github.com/natemcmaster/4a1356b53ec8d00005a6ca680da3c736. 

Note: AnyCPU won't work...you have to explicitly set a CPU architecture.

**Comment by ericsink** [comment]
Ah, so I was trying to do something that isn't actually supposed to be working just yet.  That's good info.

Looking through the csproj in that gist, that NuGetRuntimeIdentifier tag does look, er, special.

One more question:  I like how you've got the native files in runtimes/rid/native, because that is where some current (and all future?) tooling will want them to be, but you also have a .props file for backward compat.  And maybe that .props file can just go away someday.  May I assume that you are happy enough with this approach to call it a good pattern to mimic?

Thanks!

**Comment by natemcmaster** [comment]
> Looking through the csproj in that gist, that NuGetRuntimeIdentifier tag does look, er, special.

This is partly what I meant by "this is advanced stuff". The `NuGetRuntimeIdentifier` property is set explicitly to be picked up [NuGet's internal `ResolveNuGetPackageAssets` target](https://github.com/NuGet/NuGet.BuildTasks/blob/visual-studio-2015-update-3/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.targets#L144). It's what helps NuGet to know to copy the `runtimes/{rid}/native/sqlite3.dll` file into the the output folder.

The `runtime/{rid}/native/` package layout convention of NuGet 3. AFAIK NuGet 2 won't be adding support for this. The .props file is mean to polyfill the "runtimes/" folder behavior for NuGet 2. The .props file [uses the existence of a `packages.config`](https://github.com/natemcmaster/libsqlite3-package/blob/v3.12.3/src/SQLite.Native/build/net45/SQLite.Native.props#L3) file to infer that NuGet 2 is in use. It's the best way I could figure out how to detect when a project is using NuGet 2 instead of NuGet 3. It's not foolproof, but it works for the 95% of use cases.

FYI v3.12.3 will be the last version of "SQLite.Native". The next update will consolidate SQlite.Native and SQLite.Native.UWP into one package "SQLite". See https://github.com/natemcmaster/libsqlite3-package/pull/7.

**Comment by ericsink** [comment]
Cool.  Thanks for the info.
